name: Run Levanter MD Bot

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 */6 * * *' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    - name: Install dependencies
      run: |
        npm install --legacy-peer-deps

    - name: Start WhatsApp Bot
      env:
        SESSION_ID: ${{ secrets.SESSION_ID }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        SUDO: ${{ secrets.SUDO }}
        VPS: "true" # Forces the system to register as a custom VPS platform instantly
        ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      run: npm start
